---

# https://docs.ansible.com/ansible/latest/modules/apt_module.html
- name: install ntp
  apt:
    name: ntp
    state: present

# https://docs.ansible.com/ansible/latest/modules/template_module.html
- name: configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

# https://docs.ansible.com/ansible/latest/modules/service_module.html
- name: start ntp
  service:
    name: ntpd
    state: started
